In [26]:
import numpy as np

In [27]:
import array

In [28]:
np.array([1,2,34,5])

array([ 1,  2, 34,  5])

In [29]:
type(np.array([1,2,34,5])) # high order data as the convert into upcosting

numpy.ndarray

In [30]:
np.array([1,2,3,4,6.0])

array([1., 2., 3., 4., 6.])

In [31]:
np.array([1,2,3,4,6.0,'balaji'])

array(['1', '2', '3', '4', '6.0', 'balaji'], dtype='<U32')

In [32]:
np.array([[1,3],[2,3],[4,5]])

array([[1, 3],
       [2, 3],
       [4, 5]])

In [33]:
d = np.array([[[1,3],[2,3],[4,5]],[[1,3],[2,3],[4,5]]])

In [34]:
d

array([[[1, 3],
        [2, 3],
        [4, 5]],

       [[1, 3],
        [2, 3],
        [4, 5]]])

In [35]:
type(d)

numpy.ndarray

In [36]:
np.array([1,2,3],ndmin = 30) # 30 dimension

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [37]:
np.array([1,2,3],dtype=complex) # real number imaginary part s Zero

array([1.+0.j, 2.+0.j, 3.+0.j])

In [38]:
arr=np.array([[1,2],[3,4]])

In [39]:
arr

array([[1, 2],
       [3, 4]])

In [40]:
arr[0][1]

2

In [41]:
arr[1][1]

4

In [42]:
type(arr[1][1])

numpy.int32

In [43]:
mat=np.mat(arr)# changing into array to matrix

In [44]:
mat

matrix([[1, 2],
        [3, 4]])

In [45]:
l=[3,2,5,3,5]

In [46]:
np.array(l)

array([3, 2, 5, 3, 5])

In [21]:
np.asanyarray(l)

array([3, 2, 5, 3, 5])

In [47]:
np.asanyarray(mat) ## matrix

matrix([[1, 2],
        [3, 4]])

In [48]:
np.asarray(mat)# array

array([[1, 2],
       [3, 4]])

In [49]:
issubclass(np.matrix, np.ndarray)

True

In [50]:
issubclass(np.ndarray, np.matrix)

False

In [52]:
a=arr


In [53]:
a

array([[1, 2],
       [3, 4]])

In [54]:
b = np.copy(arr)  # Deep Copy


In [55]:
b

array([[1, 2],
       [3, 4]])

In [56]:
arr[0][0] = 67

In [57]:
arr

array([[67,  2],
       [ 3,  4]])

In [60]:

a        # a reflecting the changes

array([[67,  2],
       [ 3,  4]])

In [61]:
b        # b not reflecting the changes

array([[1, 2],
       [3, 4]])

In [62]:

id(arr)

2250966568176

In [63]:
id(a)

2250966568176

In [64]:
id(b)

2250966567024

In [65]:
id(arr) == id(a) # both are equal it will be reflected on b

True

In [66]:
id(arr) == id(b)

False

In [67]:

arr

array([[67,  2],
       [ 3,  4]])

In [68]:
arr[0: 10]


array([[67,  2],
       [ 3,  4]])

In [69]:
arr[-1]

array([3, 4])

In [70]:
arr[::-1]

array([[ 3,  4],
       [67,  2]])

In [71]:
for i in arr:
    print(i)

[67  2]
[3 4]


In [72]:
np.fromfunction(lambda i, j : i==j, (4,4))  #fromfunction generate ndarry from fu

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [73]:
np.fromfunction(lambda i, j : i*j, (3,3))  #fromfunction generate ndarry from function

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [74]:
np.fromfunction(lambda i, j : i+j+10, (3,3))  #fromfunction generate ndarry from fu

array([[10., 11., 12.],
       [11., 12., 13.],
       [12., 13., 14.]])

In [76]:
np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function

C:\Users\Balaji\AppData\Local\Temp\ipykernel_9652\1442271528.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function
C:\Users\Balaji\AppData\Local\Temp\ipykernel_9652\1442271528.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i, j : i/j, (3,3))  #fromfunction generate ndarry from function


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [77]:
# 0/0: nan, 1/0: inf, 2/0: inf

In [78]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [79]:
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x0000020C180A76B0>

In [80]:
def test(x):
    yield x

In [81]:
test(5)

<generator object test at 0x0000020C18E21780>

In [82]:
gen

<generator object <genexpr> at 0x0000020C180A76B0>

In [83]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [84]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [85]:
gen

<generator object <genexpr> at 0x0000020C180A76B0>

In [88]:
np.fromstring('1,3,4,5', sep=',', dtype=int)

array([1, 3, 4, 5])

In [89]:
np.fromstring('101,375,4412,512', sep=',')

array([ 101.,  375., 4412.,  512.])

In [90]:
arr = np.array(l)
arr

array([3, 2, 5, 3, 5])

In [91]:
arr.size

5

In [92]:
arr.ndim

1

In [93]:
arr.shape


(5,)

In [95]:
arr[0]

3

In [96]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [97]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [98]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [99]:

np.arange(6.6, 9, 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [100]:
np.arange(6.6, 9, -0.3)

array([], dtype=float64)

In [101]:
np.arange(9, 6.6, -0.3)    # arange dont exclude the upperbound

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [102]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [103]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [104]:
np.linspace(.3, 1.2, 5)

array([0.3  , 0.525, 0.75 , 0.975, 1.2  ])

In [105]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [106]:
np.linspace(2,4,4, endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [107]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [108]:

np.linspace([1,6], 4)

array([[1.        , 6.        ],
       [1.06122449, 5.95918367],
       [1.12244898, 5.91836735],
       [1.18367347, 5.87755102],
       [1.24489796, 5.83673469],
       [1.30612245, 5.79591837],
       [1.36734694, 5.75510204],
       [1.42857143, 5.71428571],
       [1.48979592, 5.67346939],
       [1.55102041, 5.63265306],
       [1.6122449 , 5.59183673],
       [1.67346939, 5.55102041],
       [1.73469388, 5.51020408],
       [1.79591837, 5.46938776],
       [1.85714286, 5.42857143],
       [1.91836735, 5.3877551 ],
       [1.97959184, 5.34693878],
       [2.04081633, 5.30612245],
       [2.10204082, 5.26530612],
       [2.16326531, 5.2244898 ],
       [2.2244898 , 5.18367347],
       [2.28571429, 5.14285714],
       [2.34693878, 5.10204082],
       [2.40816327, 5.06122449],
       [2.46938776, 5.02040816],
       [2.53061224, 4.97959184],
       [2.59183673, 4.93877551],
       [2.65306122, 4.89795918],
       [2.71428571, 4.85714286],
       [2.7755102 , 4.81632653],
       [2.

In [109]:
np.linspace([1,6], 4, endpoint=False, axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [110]:
np.linspace([1,6], 4, endpoint=False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [111]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [112]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [113]:
np.logspace([2],[3])

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [114]:

d = np.linspace(4,7,40)

In [115]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [116]:

d.ndim


1

In [117]:
d.shape

(40,)

In [118]:
# Changing the shape to 2d
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [119]:
d.reshape(2,1,20)   # convert in such way so that elements will remain same

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [120]:

d.reshape(2,2,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [121]:
d.reshape(2,4,5)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231],
        [4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308],
        [5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385],
        [5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462],
        [6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [122]:
np.random.rand(3)   # Gaussian/normal Distribution

array([0.18476737, 0.55058122, 0.51060242])

In [123]:
np.random.randn(5)  # standard normal distribution(mean=0, sd=1)

array([ 0.38474944,  0.48724658, -0.45451143, -0.66727384,  0.85651552])

In [124]:
np.random.randn(2,2,3)

array([[[ 0.04530027,  0.99439022,  0.33904709],
        [-0.37029443, -0.75285246, -1.29695783]],

       [[ 1.26486659,  0.81313371,  0.68745625],
        [-0.4337737 ,  1.3761861 ,  0.6041726 ]]])

In [125]:
np.random.randint(5,60)

51

In [126]:
np.random.seed(13)  # Help in get same random data for a particular argument here its 13

In [127]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [128]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [129]:
np.random.seed(13)
np.random.rand(2, 4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])