In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('titanic.csv')

In [3]:
df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [12]:
df['Age'][2]

26.0

In [13]:
df['Age'][10:100]

10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
      ... 
95     NaN
96    71.0
97    23.0
98    34.0
99    34.0
Name: Age, Length: 90, dtype: float64

In [14]:
# Statistical Data

In [15]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [16]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [17]:
df.dtypes=='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [23]:
df.dtypes[df.dtypes == 'object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [24]:
df.dtypes[df.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [25]:
# Pass the indexes of object dtype columns
d = df[df.dtypes[df.dtypes == 'object'].index]
d

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [26]:
d.describe()

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [27]:
# Cabin column we have many missing data and Embarked has 2 missing value

In [29]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:

df[['Name', 'Fare']]

Name     Fare
0                              Braund, Mr. Owen Harris   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                               Heikkinen, Miss. Laina   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                             Allen, Mr. William Henry   8.0500
..                                                 ...      ...
886                              Montvila, Rev. Juozas  13.0000
887                       Graham, Miss. Margaret Edith  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"  23.4500
889                              Behr, Mr. Karl Howell  30.0000
890                                Dooley, Mr. Patrick   7.7500

[891 rows x 2 columns]

In [31]:
type(df[['Name']])

pandas.core.frame.DataFrame

In [32]:
type(df['Name'])

pandas.core.series.Series

In [33]:
df['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [34]:
# Row where age column as null value

In [35]:

import numpy as np

In [41]:
# Row index
titanic_age_null = np.where(df['Age'].isnull() == True)
titanic_age_null

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [38]:
titanic_null=df[df['Age'].isnull() == True]
titanic_null

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [42]:
# Column filter
df[['Name', 'Pclass']]

Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
888           Johnston, Miss. Catherine Helen "Carrie"       3
889                              Behr, Mr. Karl Howell       1
890                                Dooley, Mr. Patrick       3

[891 rows x 2 columns]

In [43]:
# iloc -> integer location: pass index (row index)
df.iloc[titanic_age_null]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [44]:
df.iloc[5]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [45]:
df.iloc[[1,2,5,6]]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
5            6         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

In [46]:
# person who paid highest fare

df['Fare'] == max(df['Fare'])

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [47]:

l = [1,2,3,4]

In [48]:
pd.Series(l)


0    1
1    2
2    3
3    4
dtype: int64

In [49]:
d = {'k1': 123, 'k2':'Data2', 'k3':2+3j}

In [50]:
pd.DataFrame(d)


ValueError: If using all scalar values, you must pass an index

In [51]:
pd.DataFrame(d, index=['key', 'title', 'mail_id'])

k1     k2        k3
key      123  Data2  2.0+3.0j
title    123  Data2  2.0+3.0j
mail_id  123  Data2  2.0+3.0j

In [52]:
arr = np.random.randn(3,4)
arr

array([[ 1.40575253,  0.6378638 , -0.84160555, -0.48700199],
       [ 1.26245281, -2.96839888,  0.84500825,  0.11175657],
       [-0.88052171, -0.28308589, -0.25613992, -0.43537545]])

In [53]:
pd.DataFrame(arr)

0         1         2         3
0  1.405753  0.637864 -0.841606 -0.487002
1  1.262453 -2.968399  0.845008  0.111757
2 -0.880522 -0.283086 -0.256140 -0.435375

In [54]:
ser = pd.Series(np.array([4,5,6,7]), index = ['a', 'b', 'c', 1])


In [55]:
ser['b']

5

In [57]:
ser.iloc[1]

5

In [58]:
ser.loc['a']

4

In [59]:
ran = np.random.randint(3,6, (4,5))
ran

array([[4, 3, 4, 4, 3],
       [4, 3, 5, 5, 5],
       [5, 4, 3, 5, 4],
       [4, 5, 4, 4, 4]])

In [60]:
pd.DataFrame(ran)

0  1  2  3  4
0  4  3  4  4  3
1  4  3  5  5  5
2  5  4  3  5  4
3  4  5  4  4  4

In [62]:
df = pd.DataFrame(ran, index = ['a', 'b', 'c', 'd'], columns = ['x', 'y', 'z', '1', '2'])


In [63]:
df

x  y  z  1  2
a  4  3  4  4  3
b  4  3  5  5  5
c  5  4  3  5  4
d  4  5  4  4  4

In [64]:
df[3:][3:]

Empty DataFrame
Columns: [x, y, z, 1, 2]
Index: []

In [65]:
df.loc[['c', 'd'], ['z', '1']]

z  1
c  3  5
d  4  4

In [66]:
np.random.seed(23)
df = pd.DataFrame(np.random.randn(4,5), index = ['a', 'b', 'c', 'd'], columns = ['x', 'y', 'z', '1', '2'])
df

x         y         z         1         2
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [67]:
# Extract negative values

df.values[df.values < 0]

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [68]:
df.values

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382,  0.70167179],
       [-1.05108156, -0.36754812, -1.13745969, -1.32214752,  1.77225828],
       [-0.34745899,  0.67014016,  0.32227152,  0.06034293, -1.04345   ],
       [-1.00994188,  0.44173637,  1.12887685, -1.83806777, -0.93876863]])

In [69]:
df.values < 0

array([[False, False,  True, False, False],
       [ True,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False, False,  True,  True]])

In [70]:
# With index

for c in df.columns:
    for i in df.index:
        if df[c][i] < 0:
            print(c, i, df[c][i])

x b -1.0510815639071178
x c -0.34745899102186334
x d -1.0099418765878465
y b -0.3675481161171661
z a -0.7776194131918178
z b -1.1374596907250272
1 b -1.3221475225908594
1 d -1.8380677677579502
2 c -1.0434500017467254
2 d -0.9387686311201282


In [71]:
# With index

for c in df.columns:
    for i in df.index:
        if df[c][i] < 0:
            print(c, i, df.loc[i, c])

x b -1.0510815639071178
x c -0.34745899102186334
x d -1.0099418765878465
y b -0.3675481161171661
z a -0.7776194131918178
z b -1.1374596907250272
1 b -1.3221475225908594
1 d -1.8380677677579502
2 c -1.0434500017467254
2 d -0.9387686311201282


In [72]:
d = {'k1': [1,2,3,4,np.nan], 'k2':['data1', 'data2', np.nan,5,6], 'key3': [np.nan, np.nan, np.nan, 3, 8]}

In [73]:
df = pd.DataFrame(d)

In [74]:
df

k1     k2  key3
0  1.0  data1   NaN
1  2.0  data2   NaN
2  3.0    NaN   NaN
3  4.0      5   3.0
4  NaN      6   8.0

In [75]:
df.dropna() # Dropping all the row-axis nan rows

k1 k2  key3
3  4.0  5   3.0

In [76]:
df.dropna(axis = 1)   # Dropping columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [77]:
df

k1     k2  key3
0  1.0  data1   NaN
1  2.0  data2   NaN
2  3.0    NaN   NaN
3  4.0      5   3.0
4  NaN      6   8.0

In [78]:
df.dropna(thresh=2)

k1     k2  key3
0  1.0  data1   NaN
1  2.0  data2   NaN
3  4.0      5   3.0
4  NaN      6   8.0